version: "2.2"
services:
  ri-quickbooks-app-ws:
    image: nginx:latest
    ports:
      - 4500:80
    working_dir: /srv
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro,z"
      - "..:/srv:z"
    links:
      - ri-quickbooks-app
    networks:
      - ri-quickbooks-network

  ri-quickbooks-app:
    #image: php:7-fpm
    build:
      context: php
      dockerfile: Dockerfile
    working_dir: /srv
    volumes:
      - "..:/srv:z"
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/supervisord.conf:/etc/supervisord.conf
    depends_on:
      - ri-quickbooks-mysql
    networks:
      - ri-quickbooks-network

  ri-quickbooks-mysql:
    image: mysql:8.0.11
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=app
      - MYSQL_USER=testUser
      - MYSQL_PASSWORD=secret
    volumes:
      - ri-quickbooks-volume:/var/lib/mysql
    networks:
      - ri-quickbooks-network

  ri-quickbooks-db-admin:
    image: phpmyadmin
    restart: always
    ports:
      - 8882:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=ri-quickbooks-mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=secret
      - MAX_EXECUTION_TIME=1800
      - UPLOAD_LIMIT=2048M
    depends_on:
      - ri-quickbooks-mysql
    networks:
      - ri-quickbooks-network

  ri-quickbooks-redis:
    image: redis:alpine
    ports:
      - "63790:6379"
    networks:
      - ri-quickbooks-network

volumes:
  ri-quickbooks-volume:

#Docker Networks
networks:
  ri-quickbooks-network:
    driver: bridge
