version: "2.2"
services:
  ri-quickbooks-app-ws:
    image: nginx:latest
    working_dir: /srv
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro,z"
      - "..:/srv:z"
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    links:
      - ri-quickbooks-app
    networks:
      - ri-quickbooks-network
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ri-quickbooks-app-ws.rule=Host(`quickbooks-api.dotdropit.com`)"
      - "traefik.http.routers.ri-quickbooks-app-ws.tls=true"
      - "traefik.http.routers.ri-quickbooks-app-ws.tls.certresolver=lets-encrypt"

  ri-quickbooks-app:
    #image: php:7-fpm
    build:
      context: php
      dockerfile: Dockerfile
    working_dir: /srv
    volumes:
      - "..:/srv:z"
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/supervisord.conf:/etc/supervisord.conf
    depends_on:
      - ri-quickbooks-mysql
    networks:
      - ri-quickbooks-network
    labels:
      - traefik.enable=false

  ri-quickbooks-mysql:
    image: mysql:8.0.11
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=app
      - MYSQL_USER=testUser
      - MYSQL_PASSWORD=secret
    volumes:
      - ri-quickbooks-volume:/var/lib/mysql
    networks:
      - ri-quickbooks-network
    labels:
      - traefik.enable=false

  ri-quickbooks-db-admin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=ri-quickbooks-mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=secret
      - MAX_EXECUTION_TIME=1800
      - UPLOAD_LIMIT=2048M
    depends_on:
      - ri-quickbooks-mysql
    networks:
      - ri-quickbooks-network
    labels:
      - traefik.enable=false

  ri-quickbooks-redis:
    image: redis:alpine
    networks:
      - ri-quickbooks-network
    labels:
      - traefik.enable=false

volumes:
  ri-quickbooks-volume:

#Docker Networks
networks:
  ri-quickbooks-network:
    driver: bridge
  traefik-network:
    external: true
